name: example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_mvp:
    path: ../
  object: ^1.0.4                                # android   ios           macos   web   windows
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

object:
  baseProjectFolder: 'lib'
  outputFolder: 'data/model/generated'
  modelsFile: 'model.g.dart'
  generationClassSuffix: 'Gen'

go_mvp:
  baseProjectFolder: 'lib'
  outputFolder: 'ui'
  modelsFile: 'data/model/generated/model.g.dart'

flutter:
  uses-material-design: true
